% Import datalog file generated by vt-model
filename = 'datalog.log';
delimiterIn = '\t';
headerlinesIn = 4;
A = importdata(filename,delimiterIn,headerlinesIn);

num_tubes = 89;
num_art = 29;
tub_ind = 3*(0:num_tubes-1)+1;
Xtubes = A.data(:,tub_ind);
Xtlab = A.colheaders(tub_ind);
Ytubes = A.data(:,tub_ind+1);
Ytlab = A.colheaders(tub_ind+1);
Ztubes = A.data(:,tub_ind+2);
Ztlab = A.colheaders(tub_ind+2);
arts = A.data(:,num_tubes*3+1:end-1);
artlab = A.colheaders(num_tubes*3+1:end-1);
sound = A.data(:,end);
soundlab = A.colheaders(end);
A_rearr = [arts Xtubes Ytubes Ztubes sound];
Alab = [artlab Xtlab Ytlab Ztlab soundlab];

[m,n] = size(A_rearr);
changes = zeros(1,n);
for c=1:n
    first = A_rearr(1,c);
    for r=1:m
        if(A_rearr(r,c)~=first)
            changes(c)=1;
            break;
        end
    end
end

ch = logical(changes);
f = find(ch);
%f = 1:n;
a = (arrayfun(@(x) (A_rearr(:,x)-mean(A_rearr(:,x)))/std(A_rearr(:,x)),f,'UniformOutput',false));
A_sc = cell2mat(a);
figure(1)
imagesc(A_sc)
set(gca,'XTick',1:length(f))
set(gca,'XTickLabel',Alab(f))

