function [A_rearr, Alab, samp_freq, num_samp] = ...
import_datalog(path)
% Import datalog file generated by vt-model
%filename = 'test1/logs/datalog8.log';
delimiterIn = '\t';
headerlinesIn = 6;
A = importdata(path,delimiterIn,headerlinesIn);

samp_freq = str2double(cell2mat(A.textdata(2)));
num_samp = str2double(cell2mat(A.textdata(4)));

num_tubes = 89;
num_art = 29;
A_rearr = A.data;
Alab = A.colheaders;
% areas = A.data(:,1:num_tubes);
% arealab = A.colheaders(1:num_tubes);
% arts = A.data(:,num_tubes+1:end-1);
% artlab = A.colheaders(num_tubes+1:end-1);
% sound = A.data(:,end);
% soundlab = A.colheaders(end);
% A_rearr = [arts areas sound];
% Alab = [artlab arealab soundlab];
% *********************For Logs with Dx, Dy, Dz***************************
% tub_ind = 3*(0:num_tubes-1)+1;
% Xtubes = A.data(:,tub_ind);
% Xtlab = A.colheaders(tub_ind);
% Ytubes = A.data(:,tub_ind+1);
% Ytlab = A.colheaders(tub_ind+1);
% Ztubes = A.data(:,tub_ind+2);
% Ztlab = A.colheaders(tub_ind+2);
% XYZtubes = A.data(:,1:num_tubes*3);
% XYZlab = A.colheaders(:,1:num_tubes*3);
% arts = A.data(:,num_tubes*3+1:end-1);
% artlab = A.colheaders(num_tubes*3+1:end-1);
% sound = A.data(:,end);
% soundlab = A.colheaders(end);
% A_rearr = [arts Xtubes Ytubes Ztubes sound];
% Alab = [artlab Xtlab Ytlab Ztlab soundlab];
%A_rearr = [arts XYZtubes sound];
%Alab = [artlab XYZlab soundlab];
%nums = 6;
%A_rearr = [arts(:,1:nums) Xtubes(:,1:nums/3) Ytubes(:,1:nums/3) Ztubes(:,1:nums/3) sound];
%Alab = [artlab(:,1:nums) Xtlab(:,1:nums/3) Ytlab(:,1:nums/3) Ztlab(:,1:nums/3) soundlab];
%A_rearr = [arts(:,1:nums) XYZtubes(:,1:nums) sound];
%Alab = [artlab(:,1:nums) XYZlab(:,1:nums) soundlab];
% *******************************************************

% [m,n] = size(A_rearr);
% changes = zeros(1,n);
% for c=1:n
%     first = A_rearr(1,c);
%     for r=1:m
%         if(A_rearr(r,c)~=first)
%             changes(c)=1;
%             break;
%         end
%     end
% end
% 
% ch = logical(changes);
% f = find(ch);
% %f = 1:n;
% a = (arrayfun(@(x) (A_rearr(:,x)-mean(A_rearr(:,x)))/std(A_rearr(:,x)),f,'UniformOutput',false));
% A_sc = cell2mat(a);
% figure(1)
% imagesc(A_sc)
% set(gca,'XTick',1:length(f))
% set(gca,'XTickLabel',Alab(f))
% 
% % Play sound at upsampled frequency of 8000Hz
% up = round(8000/samp_freq);
% soundsc(interp(sound,up),samp_freq*up)

%save([testname,'/', filename(1:end-3), 'mat'],'A_rearr','Alab','samp_freq','num_samp','des_samp_freq');